---

- name: set facts
  set_fact:
    role_comment: "( {{ docker_container_name | default('selenium-grid-node') }} )"
  tags:
    - always

- name: ensure container is started {{ role_comment }}
  docker_container:
    name: "{{ docker_container_name }}"
    image: "{{ docker_image }}{% if docker_image %}:{% endif %}{{ docker_image_tag }}"
    env:
      TZ: "{{ docker_timezone }}"
  tags:
    - docker-container

- name: wait until service is ready {{ role_comment }}
  uri:
    url: "http://{{ service_selenium_grid_host }}:{{ service_selenium_grid_http_port }}/grid/console"
    return_content: true
    timeout: 300
  register: service_console
  until: service_console.content.find("Grid Console") != -1
  delay: "{{ wait_delay | default(5) }}"
  retries: 360
  tags:
    - docker-container
