---

- name: set facts
  set_fact:
    role_comment: "( {{ docker_container_name | default('selenium-grid-node') }} )"
  tags:
    - always

- name: ensure container is started {{ role_comment }}
  docker_container:
    name: "{{ docker_container_name }}"
    image: "{{ docker_image }}{% if docker_image %}:{% endif %}{{ docker_image_tag }}"
    docker_host: "{{ docker_host }}"
    published_ports: "{{ docker_published_ports }}"
    volumes: "{{ docker_volumes }}"
    shm_size: "{{ docker_shm_size }}"
    env: "{{ docker_env }}"
  tags:
    - docker-container

- name: wait until service is ready {{ role_comment }}
  uri:
    url: "{{ service_selenium_grid_status_url }}"
    return_content: true
    timeout: 300
  register: service_console
  until: service_selenium_grid_status_test in service_console.content
  delay: "{{ wait_delay | default(5) }}"
  retries: 360
  tags:
    - docker-container
